spring:
  application:
    name: webflux-gateway
server:
  port: 8081
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: lb://webflux-product
          predicates:
            - Path=/api/v1/client/**
        - id: client
          uri: lb://webflux-client
          predicates:
            - Path=/api/v1/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka