spring:
  application:
    name: webflux-product
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: webflux
      port: 27017
      host: localhost
server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka